### ISSUE TITLE
Fix broken markdown table in QGIS Tutorial

### ISSUE THREAD

**Issue by Florian-Katerndahl** [Remote-Sensing-at-FU-Berlin/Remote-Sensing-at-FU-Berlin.github.io#1]
In Chapter 1 (GUI) of the QGIS tutorial series, the table 1 doesn't render correctly.

![grafik](https://user-images.githubusercontent.com/29142246/218490281-35378a46-ff95-4399-8228-1f678d0415ed.png)

**Comment by huaqo** [comment]
[Look here](https://github.com/Remote-Sensing-at-FU-Berlin/Remote-Sensing-at-FU-Berlin.github.io/commit/8659bf5f6ebe3b729ecfdc75638f9092bff27492)
