### ISSUE TITLE
package installation shenanigans in R scripts, `raster` package and Shapefiles

### ISSUE THREAD

**Issue by Florian-Katerndahl** [Remote-Sensing-at-FU-Berlin/Remote-Sensing-at-FU-Berlin.github.io#17]
In at least one of the scripts for geodata-processing with R, the way to check if any packages need to be installed prior to loading them seems convoluted and slightly hacky.

https://github.com/Remote-Sensing-at-FU-Berlin/Remote-Sensing-at-FU-Berlin.github.io/blob/64ec3ba5368635fc202d81881d08946f91d53bcf/docs/gis/geoprocesing-and-reference-and-coordinate-systems.md?plain=1#L30-L38

Is using `requireNamespace` **outside** of package development actively used? Reading the documentation it seems this function does more than checking if a package is installed. Using `installed.packages()` seems better suited in this case, e.g.

```r
pkgs <- c("sf", "dplyr", "raster")
install.packages(pkgs[!pkgs %in% installed.packages()])
```

Additionally, the `raster` package is deprecated and superseded with the `terra` package!

Lastly, probably a bit nitpicky but why use shapefiles? Makes data handling a bit more cumbersome, no?

**Comment by Florian-Katerndahl** [comment]
@Huaqo kannst du dir das angucken/was dazu sagen?

**Comment by huaqo** [comment]
@Florian-Katerndahl I want to clarify that this is not intended to be final; it's mainly for demonstration purposes.

**requireNamespace**: I appreciate your recommendation and agree that your solution is more elegant. I'll make sure to update this accordingly.
**terra**: You're correct that I overlooked this change. I will address it soon.
**shapefiles**: I'm not quite sure what you're suggesting here; could you please provide more specific recommendations or examples? This tutorial is designed to mirror the handout from the GIS Seminar, where we work with shapefiles and demonstrate how to accomplish the same tasks using R.

Thanks for your input!

**Comment by huaqo** [comment]
Updated here: [15e5015](https://github.com/Remote-Sensing-at-FU-Berlin/Remote-Sensing-at-FU-Berlin.github.io/commit/15e501599bdacf9aa33cd03624c5dfa981a75511)

**Comment by Florian-Katerndahl** [comment]
You don't need to specify the terra package in function calls after loading it. `terra::rast` is equivalent to `rast`, given that you attached the package beforehand. Or are there any namespace collisions?

As for the shapefile export: If this is to much of a burden for students, stick with shapefiles. Otherwise: Switching to geopackages (`file.gpkg`) would result in *cleaner* exports since all data is contained in a single file and not spread across multiple ones. Other technical shortcomings of shapefiles are also mitigated this way (http://switchfromshapefile.org/)

**Comment by Florian-Katerndahl** [comment]
Seems like the decision on which file format to use needs to be made by course instructors.
