### ISSUE TITLE
Move ArcGIS Tutorial into its own repo

### ISSUE THREAD

**Issue by Florian-Katerndahl** [Remote-Sensing-at-FU-Berlin/Remote-Sensing-at-FU-Berlin.github.io#2]
Currently, the ArcGIS tutorial is located inside the Remote-Sensing-at-FU-Berlin/Remote-Sensing-at-FU-Berlin.github.io` repo.

However, it should be contained in its own repo and added as a submodule similar to the qgis and planetary science series.

**Comment by huaqo** [comment]
yes [1c1e724](https://github.com/Remote-Sensing-at-FU-Berlin/Remote-Sensing-at-FU-Berlin.github.io/commit/1c1e7249415bcadbb10ad5dadf6c9cc49897267f)
