### ISSUE TITLE
Repo duplication in `site` folder?

### ISSUE THREAD

**Issue by Florian-Katerndahl** [Remote-Sensing-at-FU-Berlin/Remote-Sensing-at-FU-Berlin.github.io#6]
All repos from `docs` are mirrored into the `site` folder. Is this expected?

**Comment by huaqo** [comment]
Yes, but its just used for live editing. I deleted it because you can just use it in a branch [b562d85](https://github.com/Remote-Sensing-at-FU-Berlin/Remote-Sensing-at-FU-Berlin.github.io/commit/b562d8593c3bb202aa44ee637592d960edb2414a)
